name: Build Docker

on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Go Packages
    strategy:
      fail-fast: true
      matrix:
        arch: [amd64, arm64, arm]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Setup JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Build
        env:
          GOOS: linux
          GOARCH: ${{ matrix.arch }}
        run: |
          go run setup.go 
          go build -o outfile/$GOOS/$GOARCH/battery-historian cmd/battery-historian/battery-historian.go
      - name: Upload to same artifact if master branch
        uses: actions/upload-artifact@v4
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          name: go-build-${{ matrix.arch }}
          path: outfile/**/*
          retention-days: 1
  docker:
    runs-on: ubuntu-latest
    needs: [build]
    name: Build and Push Docker Images for master branch
    concurrency:
      group: docker-${{ github.ref }}
      cancel-in-progress: true
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: go-build-*
          merge-multiple: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to release
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: itachi1706/battery-historian:latest